# Generated by Django 4.0.4 on 2022-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_podcast', '0003_podcasts_categories_podcasts_searching'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(default='Some String', max_length=100)),
        ),
    ]
