# Generated by Django 4.0.4 on 2022-05-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0002_companies_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='location',
        ),
    ]
