dataset = {
    'Romania': [
        {
            'year': '2019',
            'coverage': 84
        }, {
            'year': '2018',
            'coverage': 81
        }, {
            'year': '2017',
            'coverage': 76
        }, {
            'year': '2016',
            'coverage': 72
        }, {
            'year': '2015',
            'coverage': 68
        }, {
            'year': '2014',
            'coverage': 61
        }, {
            'year': '2013',
            'coverage': 58
        }, {
            'year': '2012',
            'coverage': 54
        }, {
            'year': '2011',
            'coverage': 47
        }],
    'Austria': [
        {
            'year': '2019',
            'coverage': 90
        }, {
            'year': '2018',
            'coverage': 89
        }, {
            'year': '2017',
            'coverage': 89
        }, {
            'year': '2016',
            'coverage': 85
        }, {
            'year': '2015',
            'coverage': 82
        }, {
            'year': '2014',
            'coverage': 81
        }, {
            'year': '2013',
            'coverage': 81
        }, {
            'year': '2012',
            'coverage': 79
        }, {
            'year': '2011',
            'coverage': 75
        }],
    'Albania': [
        {
            'year': '2019',
            'coverage': ':'
        }, {
            'year': '2018',
            'coverage': ':'
        }, {
            'year': '2017',
            'coverage': ':'
        }, {
            'year': '2016',
            'coverage': ':'
        }, {
            'year': '2015',
            'coverage': ':'
        }, {
            'year': '2014',
            'coverage': ':'
        }, {
            'year': '2013',
            'coverage': ':'
        }, {
            'year': '2012',
            'coverage': 84
        }, {
            'year': '2011',
            'coverage': ':'
        }],
    'Bosnia': [
        {
            'year': '2019',
            'coverage': ':'
        }, {
            'year': '2018',
            'coverage': ':'
        }, {
            'year': '2017',
            'coverage': ':'
        }, {
            'year': '2016',
            'coverage': ':'
        }, {
            'year': '2015',
            'coverage': ':'
        }, {
            'year': '2014',
            'coverage': ':'
        }, {
            'year': '2013',
            'coverage': ':'
        }, {
            'year': '2012',
            'coverage': 69
        }, {
            'year': '2011',
            'coverage': 72
        }],
    'Belgia': [
        {
            'year': '2019',
            'coverage': 90
        }, {
            'year': '2018',
            'coverage': 87
        }, {
            'year': '2017',
            'coverage': 86
        }, {
            'year': '2016',
            'coverage': 85
        }, {
            'year': '2015',
            'coverage': 82
        }, {
            'year': '2014',
            'coverage': 83
        }, {
            'year': '2013',
            'coverage': 80
        }, {
            'year': '2012',
            'coverage': 78
        }, {
            'year': '2011',
            'coverage': 77
        }],
    'Bulgaria': [
        {
            'year': '2019',
            'coverage': 75
        }, {
            'year': '2018',
            'coverage': 72
        }, {
            'year': '2017',
            'coverage': 67
        }, {
            'year': '2016',
            'coverage': 64
        }, {
            'year': '2015',
            'coverage': 59
        }, {
            'year': '2014',
            'coverage': 57
        }, {
            'year': '2013',
            'coverage': 54
        }, {
            'year': '2012',
            'coverage': 51
        }, {
            'year': '2011',
            'coverage': 45
        }],
    'Elvetia': [
        {
            'year': '2019',
            'coverage': 96
        }, {
            'year': '2018',
            'coverage': ':'
        }, {
            'year': '2017',
            'coverage': 93
        }, {
            'year': '2016',
            'coverage': ':'
        }, {
            'year': '2015',
            'coverage': ':'
        }, {
            'year': '2014',
            'coverage': 91
        }, {
            'year': '2013',
            'coverage': ':'
        }, {
            'year': '2012',
            'coverage': ':'
        }, {
            'year': '2011',
            'coverage': ':'
        }],
    'Cipru': [
        {
            'year': '2019',
            'coverage': 90
        }, {
            'year': '2018',
            'coverage': 86
        }, {
            'year': '2017',
            'coverage': 79
        }, {
            'year': '2016',
            'coverage': 74
        }, {
            'year': '2015',
            'coverage': 71
        }, {
            'year': '2014',
            'coverage': 69
        }, {
            'year': '2013',
            'coverage': 65
        }, {
            'year': '2012',
            'coverage': 62
        }, {
            'year': '2011',
            'coverage': 57
        }],
}