# Generated by Django 4.0.4 on 2022-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_podcast', '0002_podcasts_podcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='categories',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcasts',
            name='searching',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
