# Generated by Django 4.0.4 on 2022-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_podcast', '0004_podcasts_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='podcasts'),
        ),
    ]
