# Generated by Django 4.0.4 on 2022-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_podcast', '0005_alter_podcasts_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='web',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
